"""
PDF export utilities for LegalDraft AI.

Converts generated documents to professional PDF format using reportlab.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors


class PDFExporter:
    """Exports legal documents to PDF format."""
    
    def __init__(self, output_dir: Optional[str] = None):
        """
        Initialize PDF exporter.
        
        Args:
            output_dir: Directory for PDF output. Defaults to temp directory.
        """
        self.output_dir = Path(output_dir) if output_dir else Path("/tmp")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Setup styles
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles for legal documents."""
        # Title style
        self.styles.add(ParagraphStyle(
            name='LegalTitle',
            parent=self.styles['Heading1'],
            fontSize=16,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=12,
            alignment=1  # Center
        ))
        
        # Section heading style
        self.styles.add(ParagraphStyle(
            name='SectionHeading',
            parent=self.styles['Heading2'],
            fontSize=12,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=6,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        
        # Body text style
        self.styles.add(ParagraphStyle(
            name='LegalBody',
            parent=self.styles['BodyText'],
            fontSize=10,
            leading=12,
            alignment=4,  # Justify
            spaceAfter=6
        ))
    
    def _parse_document(self, content: str) -> list:
        """
        Parse document content into reportlab elements.
        
        Args:
            content: Raw document text
            
        Returns:
            List of reportlab flowable elements
        """
        elements = []
        lines = content.split('\n')
        
        for line in lines:
            line = line.strip()
            
            if not line:
                elements.append(Spacer(1, 0.1 * inch))
            elif line.isupper() and len(line.split()) < 6:
                # Treat all-caps short lines as headings
                if line.endswith(':'):
                    # Section heading
                    elements.append(Paragraph(line, self.styles['SectionHeading']))
                else:
                    # Document title
                    elements.append(Paragraph(line, self.styles['LegalTitle']))
            else:
                # Regular body text
                elements.append(Paragraph(line, self.styles['LegalBody']))
        
        return elements
    
    def create_pdf(
        self,
        content: str,
        filename: str = "document.pdf",
        page_size: str = "letter",
        margins: Optional[dict] = None
    ) -> str:
        """
        Create PDF from document content.
        
        Args:
            content: Document text content
            filename: Output filename
            page_size: Page size ('letter' or 'a4')
            margins: Dictionary with margin sizes in inches
            
        Returns:
            Path to created PDF file
        """
        # Set page size
        size = letter if page_size == "letter" else A4
        
        # Set margins
        margins = margins or {'top': 0.75, 'bottom': 0.75, 'left': 0.75, 'right': 0.75}
        
        # Create output path
        output_path = self.output_dir / filename
        
        try:
            # Create PDF document
            doc = SimpleDocTemplate(
                str(output_path),
                pagesize=size,
                topMargin=margins['top'] * inch,
                bottomMargin=margins['bottom'] * inch,
                leftMargin=margins['left'] * inch,
                rightMargin=margins['right'] * inch,
                title="Legal Document"
            )
            
            # Parse content into elements
            elements = self._parse_document(content)
            
            # Add footer with timestamp
            elements.append(Spacer(1, 0.3 * inch))
            footer_text = f"Generated by LegalDraft AI on {datetime.now().strftime('%B %d, %Y')}"
            elements.append(Paragraph(footer_text, self.styles['Normal']))
            
            # Build PDF
            doc.build(elements)
            
            return str(output_path)
        
        except Exception as e:
            raise Exception(f"PDF creation failed: {str(e)}")
    
    def create_pdf_with_signature_lines(
        self,
        content: str,
        num_signatories: int = 2,
        filename: str = "document.pdf"
    ) -> str:
        """
        Create PDF with signature lines for multiple parties.
        
        Args:
            content: Document text content
            num_signatories: Number of signature lines to add
            filename: Output filename
            
        Returns:
            Path to created PDF file
        """
        # Parse main content
        elements = self._parse_document(content)
        
        # Add page break before signatures
        elements.append(PageBreak())
        
        # Add signature section
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph("SIGNATURE PAGES", self.styles['LegalTitle']))
        elements.append(Spacer(1, 0.3 * inch))
        
        # Add signature lines for each party
        for i in range(num_signatories):
            elements.append(Paragraph(f"Party {i + 1}:", self.styles['SectionHeading']))
            elements.append(Spacer(1, 0.5 * inch))
            
            # Signature line
            elements.append(Paragraph("_" * 60, self.styles['LegalBody']))
            elements.append(Paragraph("Signature", self.styles['Normal']))
            
            elements.append(Spacer(1, 0.2 * inch))
            elements.append(Paragraph("_" * 60, self.styles['LegalBody']))
            elements.append(Paragraph("Printed Name", self.styles['Normal']))
            
            elements.append(Spacer(1, 0.2 * inch))
            elements.append(Paragraph("_" * 60, self.styles['LegalBody']))
            elements.append(Paragraph("Date", self.styles['Normal']))
            
            if i < num_signatories - 1:
                elements.append(Spacer(1, 0.4 * inch))
        
        # Create PDF
        output_path = self.output_dir / filename
        
        try:
            doc = SimpleDocTemplate(
                str(output_path),
                pagesize=letter,
                topMargin=0.75 * inch,
                bottomMargin=0.75 * inch,
                leftMargin=0.75 * inch,
                rightMargin=0.75 * inch
            )
            
            doc.build(elements)
            return str(output_path)
        
        except Exception as e:
            raise Exception(f"PDF creation with signature lines failed: {str(e)}")
    
    def cleanup_old_pdfs(self, keep_recent: int = 10):
        """
        Remove old PDF files from output directory.
        
        Args:
            keep_recent: Number of recent PDFs to keep
        """
        pdf_files = sorted(
            self.output_dir.glob("*.pdf"),
            key=lambda p: p.stat().st_mtime,
            reverse=True
        )
        
        for pdf_file in pdf_files[keep_recent:]:
            try:
                pdf_file.unlink()
            except Exception as e:
                print(f"Failed to delete {pdf_file}: {e}")
